// demos/vue-app/src/components/element-wrappers/Select.vue
<template>
  <select-element :placeholder="placeholder" v-bind:options="options"></select-element>
</template>

<script>
export default {
  name: 'Select',
  props: {
    placeholder: String,
    options: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

</style>

// demos/react-app/src/element-wrappers/Select.js
import React, { Component } from 'react';

export class Select extends Component {
  componentDidMount() {}

  componentWillUnmount() {}

  _handleRef = component => {
    this.component = component;
  };

  render() {
    return <select-element placeholder={this.props.placeholder} options={this.props.options} />;
  }
}
