// demos/vue-app/src/App.vue
<template>
  <div id="app">
    <img src="./assets/logo.png">

    <div class="main-container">
      <div class="form-container">
        <Header title="Non-Dynamic Form" />
        <card-element>
          <Input placeholder="test" />
          <Select placeholder="blah" v-bind:options="options" />
        </card-element>
      </div>

      <div class="form-container">
        <Header title="Dynamic Form" />
        <card-element>
          <DynamicForm />
        </card-element>
      </div>
    </div>
  </div>
</template>

<script>
import Header from './components/element-wrappers/Header.vue';
import Input from './components/element-wrappers/Input.vue';
import Select from './components/element-wrappers/Select.vue';
import DynamicForm from './components/element-wrappers/Dynamic-Form.vue';

export default {
  name: 'app',
  components: {
    Header,
    Input,
    Select,
    DynamicForm
  },
  props: {
    options: {
      type: String,
      default: function() {
        return JSON.stringify([
          { value: '1', viewValue: 'Value 1' },
          { value: '2', viewValue: 'Value 2' },
          { value: '3', viewValue: 'Value 3' }
        ]);
      }
    }
  }
};
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

body {
  background-color: #f0f0f1;
}

.main-container {
  display: flex;
  flex-direction: column;
}

.form-container {
  width: 500px;
  align-self: center;
  padding-bottom: 20px;
}
</style>

// demos/react-app/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import { Header } from './element-wrappers/Header';
import { Input } from './element-wrappers/Input';
import { Select } from './element-wrappers/Select';
import { DynamicForm } from './element-wrappers/Dynamic-Form';

class App extends Component {
  render() {
    var options = JSON.stringify([
      { value: '1', viewValue: 'Value 1' },
      { value: '2', viewValue: 'Value 2' },
      { value: '3', viewValue: 'Value 3' },
    ]);

    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>

        <div className="form-container">
          <Header title="Non-Dynamic Form" />
          <card-element>
            <div>
              <Input placeholder="blah" />
            </div>

            <div>
              <Input placeholder="test" />
            </div>

            <div>
              <Select placeholder="The Select" options={options} />
            </div>
          </card-element>
        </div>

        <div className="form-container">
          <Header title="Dynamic Form" />

          <card-element>
            <DynamicForm />
          </card-element>
        </div>
      </div>
    );
  }
}

export default App;
